### PR TITLE
Embedded fonts are inverted

### PR DESCRIPTION
**Pull request by albertored**

### CODE REVIEW

**Comment by Timmmm** [comment]
Oops!

**Comment by albertored** [comment]
Thanks! Are you going to publish a fixed version on npm?

**Comment by Timmmm** [comment]
I published a new version. Let me know if you have any issues.

**Comment by albertored** [comment]
Hi @Timmmm, I just tried the new version but for some reason the binary is not installed

version 1.0.2

image

version 1.0.1

image

**Comment by albertored** [comment]
Maybe you miss the `npm compile` before publishing?

**Comment by Timmmm** [comment]
Ooops, can you check version 1.0.3?

**Comment by albertored** [comment]
It works, thank you!

**Pull request merged**
